name: Deploy Node.js to Azure Web App

on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: neoswebapi                      # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src/server'              # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                               # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        cd src
        cd server
        npm install
        npm install typescript
        npx prisma generate
        tsc
    - name: Zip artifact for deployment
      run: zip release.zip ./src/server/* -r
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: release.zip
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
    - name: unzip artifact for deployment
      run: unzip release.zip
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
